services:
  postgres:
    image: postgres:17
    container_name: elive_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: elive_card
      POSTGRES_USER: elive_user
      POSTGRES_PASSWORD: Postgres@2026
    ports:
      - "5434:5432"
    volumes:
      - elive_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: elive_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elive.co.tz
      PGADMIN_DEFAULT_PASSWORD: Admin@2026
    ports:
      - "5051:80"
    depends_on:
      - postgres

volumes:
  elive_postgres_data: