<?php

namespace App\Jobs;

use App\Models\GeneratedCard;
use App\Models\Invitee;
use App\Services\CardGenerationService;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Queue\Middleware\WithoutOverlapping;
use Illuminate\Support\Str;
use Throwable;

class GenerateInviteeCardJob implements ShouldQueue
{
    use Queueable;

    public int $tries = 3;

    public int $timeout = 120;

    public int $backoff = 10;

    public function __construct(
        public int $inviteeId
    ) {}

    /**
     * Prevent the same invitee card from being generated by multiple workers at the same time.
     */
    public function middleware(): array
    {
        return [
            (new WithoutOverlapping('generate-invitee-card-' . $this->inviteeId))
                ->releaseAfter(10)
                ->expireAfter(180),
        ];
    }

    public function handle(CardGenerationService $cardGenerationService): void
    {
        $invitee = Invitee::with([
            'event.cardTemplates',
            'cardType',
            'latestGeneratedCard',
        ])->find($this->inviteeId);

        if (! $invitee) {
            return;
        }

        /*
        |--------------------------------------------------------------------------
        | Important Rule
        |--------------------------------------------------------------------------
        | Do not update invitees.card_status here.
        |
        | invitees.card_status should remain:
        | active / blocked / cancelled
        |
        | generated_cards.status should be:
        | pending / generating / generated / failed / sent
        */

        $this->prepareInviteeSecurityFields($invitee);

        $invitee->refresh();

        $this->ensureInviteeQrCode($invitee);

        $invitee->refresh();

        $generatedCard = $this->prepareGeneratedCard($invitee);

        try {
            $generatedCard->markAsGenerating();

            $cardGenerationService->generateForInvitee(
                $invitee->fresh([
                    'event.cardTemplates',
                    'cardType',
                    'latestGeneratedCard',
                ])
            );
        } catch (Throwable $exception) {
            $generatedCard->fresh()?->markAsFailed();

            throw $exception;
        }
    }

    /**
     * Automatically prepare invitee fields required before card generation.
     */
    private function prepareInviteeSecurityFields(Invitee $invitee): void
    {
        $updates = [];

        if (blank($invitee->serial_number)) {
            $updates['serial_number'] = $this->generateUniqueSerialNumber($invitee->event_id);
        }

        if (blank($invitee->short_code)) {
            $updates['short_code'] = $this->generateUniqueShortCode();
        }

        /*
        |--------------------------------------------------------------------------
        | QR Token Rule
        |--------------------------------------------------------------------------
        | qr_token should be the raw secure token.
        | qr_token_hash should be the hashed version used for validation.
        |
        | This keeps it consistent with your InviteesRelationManager.php.
        */

        if (blank($invitee->qr_token)) {
            $plainToken = Str::random(64);

            $updates['qr_token'] = $plainToken;

            if ($this->inviteeHasColumn($invitee, 'qr_token_hash')) {
                $updates['qr_token_hash'] = hash('sha256', $plainToken);
            }
        } elseif (
            $this->inviteeHasColumn($invitee, 'qr_token_hash') &&
            blank($invitee->qr_token_hash)
        ) {
            $updates['qr_token_hash'] = hash('sha256', $invitee->qr_token);
        }

        if (blank($invitee->card_status)) {
            $updates['card_status'] = Invitee::CARD_STATUS_ACTIVE ?? 'active';
        }

        if (blank($invitee->rsvp_status)) {
            $updates['rsvp_status'] = Invitee::RSVP_PENDING ?? 'pending';
        }

        if (blank($invitee->confirmed_guests)) {
            $updates['confirmed_guests'] = 0;
        }

        if (blank($invitee->checked_in_count)) {
            $updates['checked_in_count'] = 0;
        }

        if (blank($invitee->allowed_guests)) {
            $updates['allowed_guests'] = max(1, (int) ($invitee->cardType?->allowed_people ?? 1));
        }

        if (! empty($updates)) {
            $invitee->forceFill($updates)->saveQuietly();
        }
    }

    /**
     * Ensure QR image exists before card generation.
     */
    private function ensureInviteeQrCode(Invitee $invitee): void
    {
        if (method_exists($invitee, 'generateQrCode')) {
            $invitee->generateQrCode();
            return;
        }

        /*
         * Fallback:
         * If your Invitee model does not have generateQrCode(),
         * CardGenerationService should still be able to use serial_number,
         * short_code, or qr_token to generate/embed QR.
         */
    }

    /**
     * Prepare generated_cards row before actual image generation.
     */
    private function prepareGeneratedCard(Invitee $invitee): GeneratedCard
    {
        $template = $invitee->event?->cardTemplates()
            ->latest()
            ->first();

        if (! $template) {
            throw new \Exception('No card template found for this invitee event. Please upload a card template first.');
        }

        return GeneratedCard::updateOrCreate(
            [
                'invitee_id' => $invitee->id,
                'card_template_id' => $template->id,
            ],
            [
                'event_id' => $invitee->event_id,
                'status' => GeneratedCard::STATUS_GENERATING,
                'generated_at' => null,
                'sent_at' => null,
            ]
        );
    }

    /**
     * Generate unique serial number per event.
     */
    private function generateUniqueSerialNumber(?int $eventId = null): string
    {
        do {
            $serial = 'ELV-' . now()->year . '-' . strtoupper(Str::random(6));

            $query = Invitee::where('serial_number', $serial);

            if ($eventId) {
                $query->where('event_id', $eventId);
            }
        } while ($query->exists());

        return $serial;
    }

    /**
     * Generate unique private invitation short code.
     */
    private function generateUniqueShortCode(): string
    {
        do {
            $shortCode = strtoupper(Str::random(6));
        } while (Invitee::where('short_code', $shortCode)->exists());

        return $shortCode;
    }

    private function inviteeHasColumn(Invitee $invitee, string $column): bool
    {
        return in_array($column, $invitee->getConnection()
            ->getSchemaBuilder()
            ->getColumnListing($invitee->getTable()), true);
    }

    public function failed(Throwable $exception): void
    {
        $invitee = Invitee::with('latestGeneratedCard')->find($this->inviteeId);

        if (! $invitee?->latestGeneratedCard) {
            return;
        }

        $invitee->latestGeneratedCard->markAsFailed();
    }
}