<?php

namespace App\Jobs;

use App\Models\GeneratedCard;
use App\Models\Invitee;
use App\Services\AuditLogService;
use App\Services\CardGenerationService;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Queue\Middleware\WithoutOverlapping;
use Illuminate\Support\Str;
use Throwable;

class GenerateInviteeCardJob implements ShouldQueue
{
    use Queueable;

    public int $tries = 3;

    public int $timeout = 120;

    public int $backoff = 10;

    public function __construct(
        public int $inviteeId
    ) {}

    /**
     * Prevent the same invitee card from being generated by multiple workers at the same time.
     */
    public function middleware(): array
    {
        return [
            (new WithoutOverlapping('generate-invitee-card-'.$this->inviteeId))
                ->releaseAfter(10)
                ->expireAfter(180),
        ];
    }

    public function handle(CardGenerationService $cardGenerationService): void
    {
        $invitee = Invitee::with([
            'event.cardTemplates',
            'cardType',
            'latestGeneratedCard',
        ])->find($this->inviteeId);

        if (! $invitee) {
            AuditLogService::system(
                action: 'card_generation_invitee_missing',
                description: 'Card generation stopped because the invitee record could not be found.',
                metadata: [
                    'invitee_id' => $this->inviteeId,
                    'job' => self::class,
                ],
            );

            return;
        }

        /*
        |--------------------------------------------------------------------------
        | Important Rule
        |--------------------------------------------------------------------------
        | Do not update invitees.card_status here.
        |
        | invitees.card_status should remain:
        | active / blocked / cancelled
        |
        | generated_cards.status should be:
        | pending / generating / generated / failed / sent
        */

        $securityOldValues = $invitee->only([
            'serial_number',
            'short_code',
            'qr_token_hash',
            'card_status',
            'rsvp_status',
            'confirmed_guests',
            'checked_in_count',
            'allowed_guests',
        ]);

        $this->prepareInviteeSecurityFields($invitee);

        $invitee->refresh();

        $securityNewValues = $invitee->only([
            'serial_number',
            'short_code',
            'qr_token_hash',
            'card_status',
            'rsvp_status',
            'confirmed_guests',
            'checked_in_count',
            'allowed_guests',
        ]);

        if ($securityOldValues !== $securityNewValues) {
            AuditLogService::updated(
                subject: $invitee,
                eventId: $invitee->event_id,
                description: 'Invitee security and card-generation fields were prepared automatically.',
                oldValues: $securityOldValues,
                newValues: $securityNewValues,
                metadata: [
                    'source' => 'card_generation_job',
                    'job' => self::class,
                ],
            );
        }

        $this->ensureInviteeQrCode($invitee);

        $invitee->refresh();

        try {
            $generatedCard = $this->prepareGeneratedCard($invitee);
        } catch (Throwable $exception) {
            AuditLogService::record(
                action: 'card_generation.template_missing',
                subject: $invitee,
                eventId: $invitee->event_id,
                description: 'Card generation failed because no card template was available.',
                metadata: [
                    'invitee_id' => $invitee->id,
                    'serial_number' => $invitee->serial_number,
                    'error' => $exception->getMessage(),
                    'attempt' => $this->attempts(),
                ],
            );

            throw $exception;
        }

        try {
            $generatedCard->markAsGenerating();

            AuditLogService::record(
                action: 'card_generation.started',
                subject: $generatedCard,
                eventId: $invitee->event_id,
                description: 'Invitation card generation started.',
                metadata: [
                    'invitee_id' => $invitee->id,
                    'invitee_name' => $invitee->name,
                    'serial_number' => $invitee->serial_number,
                    'card_template_id' => $generatedCard->card_template_id,
                    'attempt' => $this->attempts(),
                    'job' => self::class,
                ],
            );

            $cardGenerationService->generateForInvitee(
                $invitee->fresh([
                    'event.cardTemplates',
                    'cardType',
                    'latestGeneratedCard',
                ])
            );

            $generatedCard->refresh();

            AuditLogService::record(
                action: 'card_generation.completed',
                subject: $generatedCard,
                eventId: $invitee->event_id,
                description: 'Invitation card was generated successfully.',
                metadata: [
                    'invitee_id' => $invitee->id,
                    'invitee_name' => $invitee->name,
                    'serial_number' => $invitee->serial_number,
                    'card_template_id' => $generatedCard->card_template_id,
                    'status' => $generatedCard->status,
                    'file_path' => $this->generatedCardFilePath($generatedCard),
                    'generated_at' => $generatedCard->generated_at,
                    'attempt' => $this->attempts(),
                ],
            );
        } catch (Throwable $exception) {
            $failedCard = $generatedCard->fresh();

            $failedCard?->markAsFailed();

            AuditLogService::record(
                action: 'card_generation.failed',
                subject: $failedCard ?? $generatedCard,
                eventId: $invitee->event_id,
                description: 'Invitation card generation failed.',
                metadata: [
                    'invitee_id' => $invitee->id,
                    'invitee_name' => $invitee->name,
                    'serial_number' => $invitee->serial_number,
                    'card_template_id' => $generatedCard->card_template_id,
                    'attempt' => $this->attempts(),
                    'max_attempts' => $this->tries,
                    'error' => $exception->getMessage(),
                    'exception' => $exception::class,
                ],
            );

            throw $exception;
        }
    }

    /**
     * Automatically prepare invitee fields required before card generation.
     */
    private function prepareInviteeSecurityFields(Invitee $invitee): void
    {
        $updates = [];

        if (blank($invitee->serial_number)) {
            $updates['serial_number'] = $this->generateUniqueSerialNumber($invitee->event_id);
        }

        if (blank($invitee->short_code)) {
            $updates['short_code'] = $this->generateUniqueShortCode();
        }

        /*
        |--------------------------------------------------------------------------
        | QR Token Rule
        |--------------------------------------------------------------------------
        | qr_token should be the raw secure token.
        | qr_token_hash should be the hashed version used for validation.
        */

        if (blank($invitee->qr_token)) {
            $plainToken = Str::random(64);

            $updates['qr_token'] = $plainToken;

            if ($this->inviteeHasColumn($invitee, 'qr_token_hash')) {
                $updates['qr_token_hash'] = hash('sha256', $plainToken);
            }
        } elseif (
            $this->inviteeHasColumn($invitee, 'qr_token_hash')
            && blank($invitee->qr_token_hash)
        ) {
            $updates['qr_token_hash'] = hash('sha256', $invitee->qr_token);
        }

        if (blank($invitee->card_status)) {
            $updates['card_status'] = Invitee::CARD_STATUS_ACTIVE ?? 'active';
        }

        if (blank($invitee->rsvp_status)) {
            $updates['rsvp_status'] = Invitee::RSVP_PENDING ?? 'pending';
        }

        if (blank($invitee->confirmed_guests)) {
            $updates['confirmed_guests'] = 0;
        }

        if (blank($invitee->checked_in_count)) {
            $updates['checked_in_count'] = 0;
        }

        if (blank($invitee->allowed_guests)) {
            $updates['allowed_guests'] = max(
                1,
                (int) ($invitee->cardType?->allowed_people ?? 1)
            );
        }

        if (! empty($updates)) {
            $invitee->forceFill($updates)->saveQuietly();
        }
    }

    /**
     * Ensure QR image exists before card generation.
     */
    private function ensureInviteeQrCode(Invitee $invitee): void
    {
        if (method_exists($invitee, 'generateQrCode')) {
            $oldPath = $invitee->qr_code_path ?: $invitee->qr_code;

            $invitee->generateQrCode();
            $invitee->refresh();

            $newPath = $invitee->qr_code_path ?: $invitee->qr_code;

            if ($oldPath !== $newPath || blank($oldPath)) {
                AuditLogService::record(
                    action: 'invitee.qr_prepared',
                    subject: $invitee,
                    eventId: $invitee->event_id,
                    description: 'Invitee QR code was prepared for card generation.',
                    metadata: [
                        'old_qr_path' => $oldPath,
                        'new_qr_path' => $newPath,
                        'serial_number' => $invitee->serial_number,
                    ],
                );
            }

            return;
        }

        AuditLogService::record(
            action: 'invitee.qr_generator_unavailable',
            subject: $invitee,
            eventId: $invitee->event_id,
            description: 'The Invitee model has no generateQrCode method; card generation continued using available identifiers.',
            metadata: [
                'serial_number' => $invitee->serial_number,
                'short_code' => $invitee->short_code,
            ],
        );
    }

    /**
     * Prepare generated_cards row before actual image generation.
     */
    private function prepareGeneratedCard(Invitee $invitee): GeneratedCard
    {
        $template = $invitee->event?->cardTemplates()
            ->latest()
            ->first();

        if (! $template) {
            throw new \Exception(
                'No card template found for this invitee event. Please upload a card template first.'
            );
        }

        return GeneratedCard::updateOrCreate(
            [
                'invitee_id' => $invitee->id,
                'card_template_id' => $template->id,
            ],
            [
                'event_id' => $invitee->event_id,
                'status' => GeneratedCard::STATUS_GENERATING,
                'generated_at' => null,
                'sent_at' => null,
            ]
        );
    }

    /**
     * Generate unique serial number per event.
     */
    private function generateUniqueSerialNumber(?int $eventId = null): string
    {
        do {
            $serial = 'ELV-'.now()->year.'-'.strtoupper(Str::random(6));

            $query = Invitee::where('serial_number', $serial);

            if ($eventId) {
                $query->where('event_id', $eventId);
            }
        } while ($query->exists());

        return $serial;
    }

    /**
     * Generate unique private invitation short code.
     */
    private function generateUniqueShortCode(): string
    {
        do {
            $shortCode = strtoupper(Str::random(6));
        } while (Invitee::where('short_code', $shortCode)->exists());

        return $shortCode;
    }

    private function inviteeHasColumn(Invitee $invitee, string $column): bool
    {
        return in_array(
            $column,
            $invitee->getConnection()
                ->getSchemaBuilder()
                ->getColumnListing($invitee->getTable()),
            true
        );
    }

    private function generatedCardFilePath(GeneratedCard $generatedCard): ?string
    {
        foreach ([
            'file_path',
            'card_path',
            'path',
            'generated_card_path',
        ] as $attribute) {
            $value = $generatedCard->{$attribute} ?? null;

            if (filled($value)) {
                return (string) $value;
            }
        }

        return null;
    }

    public function failed(Throwable $exception): void
    {
        $invitee = Invitee::with('latestGeneratedCard')->find($this->inviteeId);

        if (! $invitee) {
            AuditLogService::system(
                action: 'card_generation_job_failed',
                description: 'Card generation job failed after all attempts, but the invitee record was unavailable.',
                metadata: [
                    'invitee_id' => $this->inviteeId,
                    'error' => $exception->getMessage(),
                    'exception' => $exception::class,
                ],
            );

            return;
        }

        $generatedCard = $invitee->latestGeneratedCard;

        if ($generatedCard) {
            $generatedCard->markAsFailed();
        }

        AuditLogService::record(
            action: 'card_generation.permanently_failed',
            subject: $generatedCard ?? $invitee,
            eventId: $invitee->event_id,
            description: 'Invitation card generation permanently failed after all queue attempts.',
            metadata: [
                'invitee_id' => $invitee->id,
                'invitee_name' => $invitee->name,
                'serial_number' => $invitee->serial_number,
                'generated_card_id' => $generatedCard?->id,
                'max_attempts' => $this->tries,
                'error' => $exception->getMessage(),
                'exception' => $exception::class,
            ],
        );
    }
}
