<?php

namespace App\Jobs;

use App\Models\GeneratedCard;
use App\Models\Invitee;
use App\Services\CardGenerationService;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Queue\Middleware\WithoutOverlapping;
use Throwable;

class GenerateInviteeCardJob implements ShouldQueue
{
    use Queueable;

    public int $tries = 3;

    public int $timeout = 120;

    public int $backoff = 10;

    public function __construct(
        public int $inviteeId
    ) {}

    /**
     * Prevent the same invitee card from being generated by multiple jobs at the same time.
     */
    public function middleware(): array
    {
        return [
            (new WithoutOverlapping('generate-invitee-card-' . $this->inviteeId))
                ->releaseAfter(10)
                ->expireAfter(180),
        ];
    }

    public function handle(CardGenerationService $cardGenerationService): void
    {
        $invitee = Invitee::with([
            'event.cardTemplates',
        ])->find($this->inviteeId);

        if (! $invitee) {
            return;
        }

        /*
        |--------------------------------------------------------------------------
        | Important Rule
        |--------------------------------------------------------------------------
        | Do not update invitees.card_status here.
        |
        | invitees.card_status should remain:
        | active / blocked / cancelled
        |
        | generated_cards.status should be:
        | pending / generating / generated / failed / sent
        */

        $generatedCard = $this->prepareGeneratedCard($invitee);

        try {
            $generatedCard->markAsGenerating();

            $cardGenerationService->generateForInvitee(
                $invitee->fresh([
                    'event.cardTemplates',
                    'latestGeneratedCard',
                ])
            );
        } catch (Throwable $exception) {
            $generatedCard->fresh()?->markAsFailed();

            throw $exception;
        }
    }

    private function prepareGeneratedCard(Invitee $invitee): GeneratedCard
    {
        $template = $invitee->event?->cardTemplates()
            ->latest()
            ->first();

        if (! $template) {
            throw new \Exception('No card template found for this invitee event.');
        }

        return GeneratedCard::updateOrCreate(
            [
                'invitee_id' => $invitee->id,
                'card_template_id' => $template->id,
            ],
            [
                'event_id' => $invitee->event_id,
                'status' => GeneratedCard::STATUS_GENERATING,
            ]
        );
    }

    public function failed(Throwable $exception): void
    {
        $invitee = Invitee::with('latestGeneratedCard')->find($this->inviteeId);

        if (! $invitee?->latestGeneratedCard) {
            return;
        }

        $invitee->latestGeneratedCard->markAsFailed();
    }
}